// File generated by FlutterFire CLI.
// DO NOT EDIT. This file is maintained by plugins/packages/firebase_core/firebase_core_web.dart.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.web) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMEfdVZjwaNVCgUWeuTo4X6f5-sHB__to',
    appId: '1:548167696657:android:ab96913a73cf6d2f654cb0',
    messagingSenderId: '548167696657',
    projectId: 'kalorientracker-3390e',
    storageBucket: 'kalorientracker-3390e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMEfdVZjwaNVCgUWeuTo4X6f5-sHB__to',
    appId: '1:548167696657:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '548167696657',
    projectId: 'kalorientracker-3390e',
    storageBucket: 'kalorientracker-3390e.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.KalorienTracker',
  ); 

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}
